version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpass
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-local-data:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
